"""
Yaoko Flyer Getter
チラシ画像を取得し、Claude Vision で商品価格を抽出してHTMLテーブルを生成する。

使い方:
  python main.py [store_url] [--output output.html]

デフォルト店舗: https://www.yaoko-net.com/store/store06/208.html
"""

import argparse
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

from flyer_fetcher import get_latest_flyer, download_image
from image_analyzer import analyze_all_pages, Product


JST = timezone(timedelta(hours=9))

DEFAULT_STORE_URL = "https://www.yaoko-net.com/store/store06/208.html"


def format_price(product: Product) -> str:
    if product.price is None:
        return "–"
    p = int(product.price) if product.price == int(product.price) else product.price
    return f"¥{p:,}"


def build_html(products: list[Product], flyer_title: str, shop_name: str, image_urls: list[str]) -> str:
    now = datetime.now(JST).strftime("%Y年%m月%d日 %H:%M")

    rows = ""
    for p in products:
        note_html = f'<span class="note">{p.note}</span>' if p.note else ""
        rows += f"""        <tr>
          <td>{p.page}</td>
          <td class="name">{p.name}</td>
          <td class="price">{format_price(p)}</td>
          <td>{p.unit}</td>
          <td>{note_html}</td>
        </tr>\n"""

    images_html = ""
    for i, url in enumerate(image_urls, 1):
        images_html += f'<div class="flyer-img-wrap"><p>ページ {i}</p><img src="{url}" alt="チラシ {i}ページ目" loading="lazy"></div>\n'

    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{shop_name} チラシ価格表 – {flyer_title}</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: "Noto Sans JP", "Helvetica Neue", sans-serif; background: #f5f5f5; color: #222; }}
    header {{ background: #c3282b; color: #fff; padding: 1rem 1.5rem; }}
    header h1 {{ font-size: 1.4rem; }}
    header p {{ font-size: 0.85rem; opacity: 0.85; margin-top: 0.25rem; }}
    .container {{ max-width: 1100px; margin: 1.5rem auto; padding: 0 1rem; }}
    .meta {{ background: #fff; border-radius: 8px; padding: 1rem 1.5rem; margin-bottom: 1.5rem; border-left: 4px solid #c3282b; }}
    .meta p {{ font-size: 0.9rem; color: #555; }}
    table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
    thead {{ background: #c3282b; color: #fff; }}
    th, td {{ padding: 0.65rem 1rem; text-align: left; font-size: 0.9rem; }}
    th {{ font-weight: 600; }}
    td.price {{ font-weight: 700; color: #c3282b; text-align: right; white-space: nowrap; }}
    td.name {{ font-weight: 500; }}
    td:first-child {{ color: #888; font-size: 0.8rem; text-align: center; width: 3rem; }}
    tr:nth-child(even) {{ background: #fafafa; }}
    tr:hover {{ background: #fff3f3; }}
    .note {{ font-size: 0.75rem; background: #fff0c0; border-radius: 3px; padding: 1px 5px; color: #7a5a00; }}
    .flyer-section {{ margin-top: 2rem; }}
    .flyer-section h2 {{ font-size: 1.1rem; margin-bottom: 1rem; color: #555; }}
    .flyer-imgs {{ display: flex; gap: 1rem; flex-wrap: wrap; }}
    .flyer-img-wrap {{ flex: 1; min-width: 280px; background: #fff; border-radius: 8px; padding: 0.75rem; text-align: center; }}
    .flyer-img-wrap p {{ font-size: 0.8rem; color: #888; margin-bottom: 0.5rem; }}
    .flyer-img-wrap img {{ max-width: 100%; border-radius: 4px; }}
    footer {{ text-align: center; font-size: 0.75rem; color: #aaa; padding: 2rem; }}
  </style>
</head>
<body>
<header>
  <h1>🛒 {shop_name} チラシ価格表</h1>
  <p>{flyer_title}　取得日時: {now}</p>
</header>
<div class="container">
  <div class="meta">
    <p>商品数: <strong>{len(products)}</strong> 件 ／ チラシページ数: <strong>{len(image_urls)}</strong> ページ</p>
  </div>
  <table>
    <thead>
      <tr><th>P</th><th>商品名</th><th>価格</th><th>単位</th><th>備考</th></tr>
    </thead>
    <tbody>
{rows}
    </tbody>
  </table>

  <div class="flyer-section">
    <h2>📄 チラシ原本</h2>
    <div class="flyer-imgs">
      {images_html}
    </div>
  </div>
</div>
<footer>Generated by Yaoko Flyer Getter</footer>
</body>
</html>"""


def main():
    parser = argparse.ArgumentParser(description="ヤオコーチラシ価格表生成ツール")
    parser.add_argument(
        "store_url",
        nargs="?",
        default=DEFAULT_STORE_URL,
        help=f"店舗ページURL (デフォルト: {DEFAULT_STORE_URL})",
    )
    parser.add_argument(
        "--output", "-o",
        default="flyer_output.html",
        help="出力HTMLファイルパス (デフォルト: flyer_output.html)",
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("ANTHROPIC_API_KEY"),
        help="Anthropic APIキー (環境変数 ANTHROPIC_API_KEY でも可)",
    )
    args = parser.parse_args()

    if not args.api_key:
        print("エラー: ANTHROPIC_API_KEY が設定されていません。", file=sys.stderr)
        print("  環境変数か --api-key オプションで指定してください。", file=sys.stderr)
        sys.exit(1)

    print(f"📡 チラシ情報を取得中: {args.store_url}")
    flyer = get_latest_flyer(args.store_url)
    print(f"✅ 取得完了: [{flyer.shop_name}] {flyer.title}")
    print(f"   画像ページ数: {len(flyer.image_urls)}")

    print("⬇️  チラシ画像をダウンロード中...")
    images = []
    for i, url in enumerate(flyer.image_urls, 1):
        print(f"   ページ {i}: {url}")
        images.append(download_image(url))

    print("🤖 Claude Vision で商品価格を解析中...")
    products = analyze_all_pages(images, api_key=args.api_key)
    print(f"✅ {len(products)} 件の商品を抽出しました")

    print("📝 HTML を生成中...")
    html = build_html(products, flyer.title, flyer.shop_name, flyer.image_urls)
    Path(args.output).write_text(html, encoding="utf-8")
    print(f"✅ 完了: {args.output}")


if __name__ == "__main__":
    main()
